<?xml version="1.0" encoding="utf-8"?>
<Content Key="ca9bca5f-2afa-4a9e-bea5-147f5b01d19f" Alias="Application insights fix" Level="4">
  <Info>
    <Parent Key="fa6439c3-1697-4002-919b-13d88db5a30f">Umbraco</Parent>
    <Path>/Start/Blogs/Umbraco/ApplicationInsightsFix</Path>
    <Trashed>false</Trashed>
    <ContentType>blogPostPage</ContentType>
    <CreateDate>2020-01-29T13:21:26</CreateDate>
    <NodeName Default="Application insights fix" />
    <SortOrder>7</SortOrder>
    <Published Default="true" />
    <Schedule />
    <Template Key="58a30bec-739d-43b7-b66f-85ca2620dd3e">BlogPostPage</Template>
  </Info>
  <Properties>
    <heroImage>
      <Value><![CDATA[]]></Value>
    </heroImage>
    <mainBody>
      <Value><![CDATA[<p>When adding Application Insights to a clients App Service a site breaking error was unexpectedly thrown. The error read:</p>
<pre>The process cannot access the file 'D:\home\site\wwwroot\App_Data\TEMP\PluginCache\umbraco-plugins.RD0003FF8F3E23.hash' because it is being used by another process.</pre>
<p><strong>The solution </strong>was to simply delete the file mentioned in the error message.</p>
<p>For the production environment I tried deleting the files beforehand in order to skip the error message entirely, but that was unfortunately not possible. You have to activate Application Insights to the App Service and <span style="text-decoration: underline;">then</span> you can delete the file(s) (You can delete the entire content of the folder if you want to).</p>
<p>I did this for the dev/test environment first and allowed the site to run for a day or two to see if the error would reappear when the temporary file it complained about would get regenerated. The error did not reappear.</p>
<p>So, when activating Application Insights for your website, keep in mind that an error message can be thrown. But now you know how to fix it!</p>
<p> </p>]]></Value>
    </mainBody>
    <metaDescription>
      <Value><![CDATA[Solution for the error when adding Application Insights to your Umbraco App Service. The error message that is thrown looks like this: "The process cannot access the file 'D:\home\site\wwwroot\App_Data\TEMP\PluginCache\umbraco-plugins.{FileName}.hash' because it is being used by another process".]]></Value>
    </metaDescription>
    <metaTitle>
      <Value><![CDATA[]]></Value>
    </metaTitle>
    <preamble>
      <Value><![CDATA[How to solve an exception that can get thrown when activating Application Insights in Azure for your website.]]></Value>
    </preamble>
    <teaserHeading>
      <Value><![CDATA[]]></Value>
    </teaserHeading>
    <teaserMedia>
      <Value><![CDATA[{"src":"/media/5ged2ean/bingimageoftheday.jpg","focalPoint":{"left":0.5,"top":0.5},"crops":[{"alias":"startPage","width":500,"height":500,"coordinates":null}]}]]></Value>
    </teaserMedia>
    <teaserMediaAltText>
      <Value><![CDATA[]]></Value>
    </teaserMediaAltText>
    <title>
      <Value><![CDATA[Solve Application Insights error in Umbraco]]></Value>
    </title>
  </Properties>
</Content>